# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZApHYJV-y9Ig_K3wB7Fd4-XyLfeufU8F
"""

# ============================================================
# OBSERVED-VARIABLE LONGITUDINAL PATH ANALYSIS PIPELINE
# FOR GOOGLE COLAB
# ============================================================
# This version is written specifically for the uploaded dataset:
#   longitudinal_bullying_withdrawal_data.csv
#
# Expected columns:
#   id
#   age
#   gender
#   parent_edu
#   low_income
#   recruit_source
#   offline_bullying_T1
#   cyberbullying_T1
#   family_support_T1
#   strong_tie_withdrawal_T2
#   neutral_tie_withdrawal_T2
#   depression_T1
#   anxiety_T1
#   stress_T1
#   depression_T3
#   anxiety_T3
#   stress_T3
#
# Main outputs:
#   - descriptive statistics
#   - correlation table
#   - path models
#   - bootstrap indirect effects
#   - Wald-style comparison of cyber vs offline bullying
#   - sensitivity model
#   - VIF diagnostics
#   - figures
#   - CSV and LaTeX tables
# ============================================================

# -----------------------------
# Install packages
# -----------------------------
import sys
import subprocess


def pip_install(packages):
    """Install required packages quietly."""
    for package in packages:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])


REQUIRED_PACKAGES = [
    "numpy",
    "pandas",
    "scipy",
    "matplotlib",
    "statsmodels",
    "openpyxl",
]
pip_install(REQUIRED_PACKAGES)

# -----------------------------
# Imports
# -----------------------------
import os
import random
import shutil
import warnings
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd
import scipy.stats as st
import matplotlib.pyplot as plt

import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
from matplotlib.patches import FancyBboxPatch
from matplotlib.lines import Line2D

warnings.filterwarnings("ignore")

# ============================================================
# GLOBAL SETTINGS
# ============================================================

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
random.seed(RANDOM_SEED)

BASE_DIR = Path("/content/project_bullying_observed")
DATA_DIR = BASE_DIR / "data"
OUT_DIR = BASE_DIR / "output"
TABLE_DIR = OUT_DIR / "tables"
FIG_DIR = OUT_DIR / "figures"
LOG_DIR = OUT_DIR / "logs"

for path in [BASE_DIR, DATA_DIR, OUT_DIR, TABLE_DIR, FIG_DIR, LOG_DIR]:
    path.mkdir(parents=True, exist_ok=True)

plt.rcParams.update({
    "figure.dpi": 160,
    "savefig.dpi": 300,
    "font.size": 11,
    "axes.titlesize": 14,
    "axes.labelsize": 11,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    "legend.fontsize": 10,
    "font.family": "DejaVu Sans",
    "axes.linewidth": 1.0,
})

# ============================================================
# CONFIGURATION
# ============================================================

CONFIG = {
    "data_file": None,  # optional explicit path; otherwise upload in Colab or use default path
    "default_filename": "longitudinal_bullying_withdrawal_data.csv",

    "id_col": "id",
    "age_col": "age",
    "gender_col": "gender",
    "parent_edu_col": "parent_edu",
    "low_income_col": "low_income",
    "recruit_source_col": "recruit_source",

    "offline_col": "offline_bullying_T1",
    "cyber_col": "cyberbullying_T1",
    "family_col": "family_support_T1",

    "strong_withdraw_col": "strong_tie_withdrawal_T2",
    "neutral_withdraw_col": "neutral_tie_withdrawal_T2",

    "dep_t1_col": "depression_T1",
    "anx_t1_col": "anxiety_T1",
    "stress_t1_col": "stress_T1",

    "dep_t3_col": "depression_T3",
    "anx_t3_col": "anxiety_T3",
    "stress_t3_col": "stress_T3",

    "missing_tokens": ["", "NA", "N/A", "na", "n/a", "missing", ".", " "],

    "n_boot": 2000,
    "bootstrap_seed": 123,
}

# ============================================================
# HELPERS
# ============================================================

def write_text(path: Path, text: str) -> None:
    """Write UTF-8 text to disk."""
    path.write_text(text, encoding="utf-8")


def save_csv(df: pd.DataFrame, path: Path, index: bool = False) -> None:
    """Save DataFrame to CSV."""
    df.to_csv(path, index=index)


def save_latex(df: pd.DataFrame, path: Path, caption: str = None, label: str = None) -> None:
    """Save DataFrame as a LaTeX table."""
    latex = df.to_latex(
        index=False,
        escape=False,
        caption=caption,
        label=label,
        float_format=lambda x: f"{x:.3f}" if isinstance(x, (float, np.floating)) else str(x),
    )
    write_text(path, latex)


def pretty_p(p: float) -> str:
    """Pretty p-value formatter for figures and text."""
    if pd.isna(p):
        return ""
    if p < 0.001:
        return "< .001"
    return f"= {p:.3f}".replace("0.", ".")


def zscore(series: pd.Series) -> pd.Series:
    """Population-standardized z-score."""
    mean = series.mean(skipna=True)
    sd = series.std(skipna=True, ddof=0)
    if pd.isna(sd) or sd == 0:
        return pd.Series(np.nan, index=series.index)
    return (series - mean) / sd


def add_constant(df: pd.DataFrame) -> pd.DataFrame:
    """Add constant safely."""
    return sm.add_constant(df, has_constant="add")


def p_label(p):
    """Mathtext-ready p label."""
    if pd.isna(p):
        return ""
    if p < 0.001:
        return r"$p<.001$"
    return rf"$p={p:.3f}$".replace("0.", ".")


def beta_label(beta):
    """Mathtext-ready beta label."""
    if pd.isna(beta):
        return ""
    return rf"$\beta={beta:.2f}$".replace("0.", ".").replace("-0.", "-.")


# ============================================================
# DATA LOADING
# ============================================================

def resolve_data_file(config: dict) -> Path:
    """Resolve dataset location, or request upload in Colab."""
    explicit = config.get("data_file", None)
    if explicit is not None:
        explicit_path = Path(explicit)
        if explicit_path.exists():
            print(f"Using dataset from explicit path: {explicit_path}")
            return explicit_path

    default_path = DATA_DIR / config["default_filename"]
    if default_path.exists():
        print(f"Using dataset from default path: {default_path}")
        return default_path

    try:
        from google.colab import files as colab_files  # type: ignore
        print("Dataset not found in the default location.")
        print("Please upload your CSV dataset now.")
        uploaded = colab_files.upload()

        if not uploaded:
            raise FileNotFoundError("No file was uploaded.")

        uploaded_name = list(uploaded.keys())[0]
        uploaded_path = Path("/content") / uploaded_name

        target_path = DATA_DIR / config["default_filename"]
        shutil.copy(uploaded_path, target_path)

        print(f"Uploaded dataset saved to: {target_path}")
        return target_path

    except Exception as exc:
        raise FileNotFoundError(
            "Dataset could not be located.\n"
            f"Explicit path: {explicit}\n"
            f"Default path: {default_path}\n"
            f"Upload error: {exc}"
        )


def load_data(config: dict) -> pd.DataFrame:
    """Load CSV and normalize missing values."""
    data_file = resolve_data_file(config)
    df = pd.read_csv(data_file)

    for token in config["missing_tokens"]:
        df = df.replace(token, np.nan)

    for col in df.columns:
        try:
            df[col] = pd.to_numeric(df[col], errors="ignore")
        except Exception:
            pass

    print(f"Loaded dataset shape: {df.shape}")
    print("Columns:")
    for c in df.columns:
        print(" -", c)

    return df


def validate_columns(df: pd.DataFrame, config: dict) -> None:
    """Check required columns."""
    required = [
        config["id_col"],
        config["age_col"],
        config["gender_col"],
        config["parent_edu_col"],
        config["low_income_col"],
        config["recruit_source_col"],
        config["offline_col"],
        config["cyber_col"],
        config["family_col"],
        config["strong_withdraw_col"],
        config["neutral_withdraw_col"],
        config["dep_t1_col"],
        config["anx_t1_col"],
        config["stress_t1_col"],
        config["dep_t3_col"],
        config["anx_t3_col"],
        config["stress_t3_col"],
    ]

    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError("Missing required columns:\n" + "\n".join(missing))

# ============================================================
# PREPARE ANALYSIS DATA
# ============================================================

def prepare_analysis_data(df: pd.DataFrame, config: dict) -> pd.DataFrame:
    """Create composite mediator and standardized moderation terms."""
    out = df.copy()

    out["withdrawal_T2"] = out[
        [config["strong_withdraw_col"], config["neutral_withdraw_col"]]
    ].mean(axis=1)

    out["offline_z"] = zscore(out[config["offline_col"]])
    out["cyber_z"] = zscore(out[config["cyber_col"]])
    out["family_z"] = zscore(out[config["family_col"]])
    out["withdrawal_z"] = zscore(out["withdrawal_T2"])

    out["offline_x_family"] = out["offline_z"] * out["family_z"]
    out["cyber_x_family"] = out["cyber_z"] * out["family_z"]

    return out

# ============================================================
# DESCRIPTIVES
# ============================================================

def build_descriptive_table(df: pd.DataFrame, config: dict) -> pd.DataFrame:
    """Descriptive summary for main variables."""
    variables = [
        config["offline_col"],
        config["cyber_col"],
        config["strong_withdraw_col"],
        config["neutral_withdraw_col"],
        config["family_col"],
        config["dep_t3_col"],
        config["anx_t3_col"],
        config["stress_t3_col"],
    ]

    rows = []
    for var in variables:
        rows.append({
            "Variable": var,
            "M": df[var].mean(skipna=True),
            "SD": df[var].std(skipna=True),
            "Min": df[var].min(skipna=True),
            "Max": df[var].max(skipna=True),
            "N_nonmissing": df[var].notna().sum(),
        })
    return pd.DataFrame(rows)


def build_correlation_table(df: pd.DataFrame, config: dict) -> pd.DataFrame:
    """Zero-order correlation matrix."""
    variables = [
        config["offline_col"],
        config["cyber_col"],
        config["strong_withdraw_col"],
        config["neutral_withdraw_col"],
        config["family_col"],
        config["dep_t3_col"],
        config["anx_t3_col"],
        config["stress_t3_col"],
    ]
    corr = df[variables].corr()
    return corr.reset_index().rename(columns={"index": "Variable"})

# ============================================================
# VIF
# ============================================================

def build_vif_table(df: pd.DataFrame, config: dict) -> pd.DataFrame:
    """Variance inflation factor table."""
    cols = [
        config["age_col"],
        config["gender_col"],
        config["parent_edu_col"],
        config["low_income_col"],
        config["recruit_source_col"],
        config["offline_col"],
        config["cyber_col"],
        config["family_col"],
        "withdrawal_T2",
    ]

    data = df[cols].apply(pd.to_numeric, errors="coerce").dropna()
    if data.shape[0] < 10:
        return pd.DataFrame(columns=["Variable", "VIF"])

    X = add_constant(data)
    rows = []
    for i, col in enumerate(X.columns):
        if col == "const":
            continue
        rows.append({
            "Variable": col,
            "VIF": variance_inflation_factor(X.values, i),
        })

    return pd.DataFrame(rows)

# ============================================================
# REGRESSION HELPERS
# ============================================================

def fit_ols(y: pd.Series, X: pd.DataFrame):
    """Fit OLS after dropping missing rows."""
    data = pd.concat([y, X], axis=1).dropna()
    y_clean = data.iloc[:, 0]
    X_clean = add_constant(data.iloc[:, 1:])
    model = sm.OLS(y_clean, X_clean).fit()
    return model, data


def summarize_model(model, label: str) -> pd.DataFrame:
    """Turn model output into a compact DataFrame."""
    rows = []
    for term in model.params.index:
        rows.append({
            "Model": label,
            "Term": term,
            "B": model.params[term],
            "SE": model.bse[term],
            "t": model.tvalues[term],
            "p": model.pvalues[term],
        })
    return pd.DataFrame(rows)


def standardized_beta_from_model(model, data: pd.DataFrame, x_name: str, y_name: str) -> float:
    """Convert an unstandardized coefficient to a standardized beta."""
    if x_name not in model.params.index or x_name not in data.columns or y_name not in data.columns:
        return np.nan

    x = pd.to_numeric(data[x_name], errors="coerce")
    y = pd.to_numeric(data[y_name], errors="coerce")
    valid = pd.concat([x, y], axis=1).dropna()

    if valid.shape[0] < 5:
        return np.nan

    sx = valid.iloc[:, 0].std(ddof=0)
    sy = valid.iloc[:, 1].std(ddof=0)

    if sx == 0 or sy == 0 or pd.isna(sx) or pd.isna(sy):
        return np.nan

    return float(model.params[x_name] * sx / sy)

# ============================================================
# MAIN MODELS
# ============================================================

def fit_withdrawal_model(df: pd.DataFrame, config: dict):
    """Primary mediator model."""
    y = df["withdrawal_T2"]
    X = df[[
        config["offline_col"],
        config["cyber_col"],
        config["family_col"],
        "offline_x_family",
        "cyber_x_family",
        config["age_col"],
        config["gender_col"],
        config["parent_edu_col"],
        config["low_income_col"],
        config["recruit_source_col"],
    ]]
    return fit_ols(y, X)


def fit_outcome_model(df: pd.DataFrame, config: dict, outcome_t3: str, outcome_t1: str):
    """Outcome model with composite withdrawal mediator."""
    y = df[outcome_t3]
    X = df[[
        "withdrawal_T2",
        config["offline_col"],
        config["cyber_col"],
        outcome_t1,
        config["age_col"],
        config["gender_col"],
        config["parent_edu_col"],
        config["low_income_col"],
        config["recruit_source_col"],
    ]]
    return fit_ols(y, X)


def fit_sensitivity_model(df: pd.DataFrame, config: dict, outcome_t3: str, outcome_t1: str):
    """Outcome model with strong/neutral withdrawal entered separately."""
    y = df[outcome_t3]
    X = df[[
        config["strong_withdraw_col"],
        config["neutral_withdraw_col"],
        config["offline_col"],
        config["cyber_col"],
        outcome_t1,
        config["age_col"],
        config["gender_col"],
        config["parent_edu_col"],
        config["low_income_col"],
        config["recruit_source_col"],
    ]]
    return fit_ols(y, X)

# ============================================================
# BOOTSTRAP INDIRECT EFFECTS
# ============================================================

def bootstrap_indirect_effects(df: pd.DataFrame, config: dict) -> pd.DataFrame:
    """Bootstrap indirect effects using refit models on resamples."""
    rng = np.random.default_rng(config["bootstrap_seed"])
    n = len(df)
    rows = []

    for _ in range(config["n_boot"]):
        sample_idx = rng.integers(0, n, size=n)
        sample = df.iloc[sample_idx].copy()

        sample["withdrawal_T2"] = sample[
            [config["strong_withdraw_col"], config["neutral_withdraw_col"]]
        ].mean(axis=1)
        sample["offline_z"] = zscore(sample[config["offline_col"]])
        sample["cyber_z"] = zscore(sample[config["cyber_col"]])
        sample["family_z"] = zscore(sample[config["family_col"]])
        sample["offline_x_family"] = sample["offline_z"] * sample["family_z"]
        sample["cyber_x_family"] = sample["cyber_z"] * sample["family_z"]

        try:
            withdrawal_model, _ = fit_withdrawal_model(sample, config)
            dep_model, _ = fit_outcome_model(sample, config, config["dep_t3_col"], config["dep_t1_col"])
            anx_model, _ = fit_outcome_model(sample, config, config["anx_t3_col"], config["anx_t1_col"])
            stress_model, _ = fit_outcome_model(sample, config, config["stress_t3_col"], config["stress_t1_col"])

            a_off = withdrawal_model.params.get(config["offline_col"], np.nan)
            a_cyb = withdrawal_model.params.get(config["cyber_col"], np.nan)

            b_dep = dep_model.params.get("withdrawal_T2", np.nan)
            b_anx = anx_model.params.get("withdrawal_T2", np.nan)
            b_stress = stress_model.params.get("withdrawal_T2", np.nan)

            rows.append({
                "offline_ind_dep": a_off * b_dep,
                "offline_ind_anx": a_off * b_anx,
                "offline_ind_stress": a_off * b_stress,
                "cyber_ind_dep": a_cyb * b_dep,
                "cyber_ind_anx": a_cyb * b_anx,
                "cyber_ind_stress": a_cyb * b_stress,
                "offline_to_withdrawal": a_off,
                "cyber_to_withdrawal": a_cyb,
            })
        except Exception:
            continue

    boot = pd.DataFrame(rows)
    if boot.empty:
        raise RuntimeError("Bootstrap failed for all resamples.")

    summary_rows = []
    for col in boot.columns:
        arr = boot[col].dropna().values
        ci_low, ci_high = np.percentile(arr, [2.5, 97.5])
        prop_le_zero = np.mean(arr <= 0)
        prop_ge_zero = np.mean(arr >= 0)
        p_two = min(1.0, 2 * min(prop_le_zero, prop_ge_zero))

        summary_rows.append({
            "Effect": col,
            "Boot_N": len(arr),
            "Mean": np.mean(arr),
            "SE": np.std(arr, ddof=1),
            "CI_low": ci_low,
            "CI_high": ci_high,
            "p_two_tailed_approx": p_two,
        })

    return pd.DataFrame(summary_rows)


def build_wald_table(withdrawal_model, config: dict) -> pd.DataFrame:
    """Proper Wald-style comparison from the fitted withdrawal model covariance matrix."""
    b_off = withdrawal_model.params.get(config["offline_col"], np.nan)
    b_cyb = withdrawal_model.params.get(config["cyber_col"], np.nan)

    cov = withdrawal_model.cov_params()

    if (
        pd.isna(b_off)
        or pd.isna(b_cyb)
        or config["offline_col"] not in cov.index
        or config["cyber_col"] not in cov.index
    ):
        return pd.DataFrame([{
            "Contrast": "Cyber vs Offline on Withdrawal",
            "Diff_mean": np.nan,
            "Diff_SE": np.nan,
            "Wald_chi2_1df": np.nan,
            "p_value": np.nan,
            "CI_low": np.nan,
            "CI_high": np.nan,
        }])

    var_off = cov.loc[config["offline_col"], config["offline_col"]]
    var_cyb = cov.loc[config["cyber_col"], config["cyber_col"]]
    cov_off_cyb = cov.loc[config["offline_col"], config["cyber_col"]]

    diff = b_cyb - b_off
    var_diff = var_cyb + var_off - 2 * cov_off_cyb

    if pd.isna(var_diff) or var_diff <= 0:
        diff_se = np.nan
        wald = np.nan
        p_value = np.nan
        ci_low = np.nan
        ci_high = np.nan
    else:
        diff_se = float(np.sqrt(var_diff))
        wald = float((diff / diff_se) ** 2)
        p_value = float(st.chi2.sf(wald, 1))
        ci_low = float(diff - 1.96 * diff_se)
        ci_high = float(diff + 1.96 * diff_se)

    return pd.DataFrame([{
        "Contrast": "Cyber vs Offline on Withdrawal",
        "Diff_mean": float(diff),
        "Diff_SE": diff_se,
        "Wald_chi2_1df": wald,
        "p_value": p_value,
        "CI_low": ci_low,
        "CI_high": ci_high,
    }])


def rename_bootstrap_effects(boot_df: pd.DataFrame) -> pd.DataFrame:
    """Human-readable names for bootstrap effects."""
    mapping = {
        "offline_ind_dep": "Offline bullying -> Withdrawal -> Depression",
        "offline_ind_anx": "Offline bullying -> Withdrawal -> Anxiety",
        "offline_ind_stress": "Offline bullying -> Withdrawal -> Stress",
        "cyber_ind_dep": "Cyberbullying -> Withdrawal -> Depression",
        "cyber_ind_anx": "Cyberbullying -> Withdrawal -> Anxiety",
        "cyber_ind_stress": "Cyberbullying -> Withdrawal -> Stress",
        "offline_to_withdrawal": "Offline bullying -> Withdrawal",
        "cyber_to_withdrawal": "Cyberbullying -> Withdrawal",
    }
    out = boot_df.copy()
    out["Effect"] = out["Effect"].map(mapping).fillna(out["Effect"])
    return out

# ============================================================
# RESIDUAL DIAGNOSTICS
# ============================================================

def make_residual_diagnostics(model, name: str):
    """Create residual histogram and QQ plot."""
    resid = model.resid

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.hist(resid, bins=30, edgecolor="black")
    ax.set_title(f"Residual Distribution: {name}")
    ax.set_xlabel("Residual")
    ax.set_ylabel("Frequency")
    fig.savefig(FIG_DIR / f"diagnostic_hist_{name}.png", bbox_inches="tight", facecolor="white")
    plt.close(fig)

    fig = plt.figure(figsize=(6.5, 6.5))
    ax = fig.add_subplot(111)
    sm.qqplot(resid, line="45", ax=ax)
    ax.set_title(f"Q-Q Plot: {name}")
    fig.savefig(FIG_DIR / f"diagnostic_qq_{name}.png", bbox_inches="tight", facecolor="white")
    plt.close(fig)

# ============================================================
# FIGURE HELPERS
# ============================================================

def add_box(ax, x, y, w, h, text, fontsize=11, lw=1.4):
    """Add rounded annotation box in axes coordinates."""
    patch = FancyBboxPatch(
        (x, y), w, h,
        boxstyle="round,pad=0.02,rounding_size=0.02",
        linewidth=lw,
        edgecolor="black",
        facecolor="white",
        transform=ax.transAxes,
        clip_on=False,
    )
    ax.add_patch(patch)
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=fontsize, transform=ax.transAxes)


def add_arrow(ax, x1, y1, x2, y2, text=None, tx=None, ty=None, lw=1.5, ls="-", fontsize=10):
    """Add arrow with optional label."""
    ax.annotate(
        "",
        xy=(x2, y2), xytext=(x1, y1),
        xycoords=ax.transAxes, textcoords=ax.transAxes,
        arrowprops=dict(arrowstyle="->", lw=lw, linestyle=ls, color="black"),
    )
    if text is not None:
        tx = (x1 + x2) / 2 if tx is None else tx
        ty = (y1 + y2) / 2 if ty is None else ty
        ax.text(tx, ty, text, ha="center", va="center", fontsize=fontsize, transform=ax.transAxes)

# ============================================================
# FIGURES
# ============================================================

def make_figure1():
    """Conceptual model figure."""
    fig, ax = plt.subplots(figsize=(12, 6.2))
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")

    add_box(ax, 0.06, 0.57, 0.22, 0.18, "Bullying Victimization\n(T1)\n\nOffline bullying\nCyberbullying", fontsize=11)
    add_box(ax, 0.39, 0.57, 0.22, 0.18, "Social Withdrawal\n(T2)\n\nStrong-tie withdrawal\nNeutral-tie withdrawal", fontsize=11)
    add_box(ax, 0.72, 0.49, 0.22, 0.32, "Internalizing Symptoms\n(T3)\n\nDepression\nAnxiety\nStress", fontsize=11)
    add_box(ax, 0.39, 0.20, 0.22, 0.13, "Family Support\n(T1)\nModerator", fontsize=11)

    add_arrow(ax, 0.28, 0.66, 0.39, 0.66, text="H1, H3", ty=0.72)
    add_arrow(ax, 0.61, 0.66, 0.72, 0.66, text="H2", ty=0.72)
    add_arrow(ax, 0.50, 0.33, 0.50, 0.57, text="H4", tx=0.56, ty=0.45, lw=1.4)
    add_arrow(ax, 0.28, 0.60, 0.72, 0.57, text="Direct path", tx=0.50, ty=0.53, ls="--", lw=1.2)

    ax.text(
        0.5, 0.07,
        "Covariates in primary models: age, gender, parental education,\n"
        "low income, recruitment source, and baseline outcome levels.",
        ha="center", va="center", transform=ax.transAxes, fontsize=10,
    )

    ax.set_title("Conceptual Model", pad=14)
    fig.savefig(FIG_DIR / "figure1_conceptual_model.png", bbox_inches="tight", facecolor="white")
    plt.close(fig)


def make_figure2(withdrawal_model, withdrawal_data, dep_model, dep_data, anx_model, anx_data, stress_model, stress_data, wald_df, config: dict):
    """Observed-variable path figure aligned with final article logic and reported results."""
    beta_off = standardized_beta_from_model(
        withdrawal_model, withdrawal_data, config["offline_col"], "withdrawal_T2"
    )
    beta_cyb = standardized_beta_from_model(
        withdrawal_model, withdrawal_data, config["cyber_col"], "withdrawal_T2"
    )
    beta_w_to_dep = standardized_beta_from_model(
        dep_model, dep_data, "withdrawal_T2", config["dep_t3_col"]
    )
    beta_w_to_anx = standardized_beta_from_model(
        anx_model, anx_data, "withdrawal_T2", config["anx_t3_col"]
    )
    beta_w_to_stress = standardized_beta_from_model(
        stress_model, stress_data, "withdrawal_T2", config["stress_t3_col"]
    )

    p_off = withdrawal_model.pvalues.get(config["offline_col"], np.nan)
    p_cyb = withdrawal_model.pvalues.get(config["cyber_col"], np.nan)
    p_w_dep = dep_model.pvalues.get("withdrawal_T2", np.nan)
    p_w_anx = anx_model.pvalues.get("withdrawal_T2", np.nan)
    p_w_stress = stress_model.pvalues.get("withdrawal_T2", np.nan)

    # Standardized moderation panel specifically for cyberbullying × family support
    mod_df = withdrawal_data.copy()
    mod_df["withdrawal_z"] = zscore(mod_df["withdrawal_T2"])
    mod_df["cyber_z"] = zscore(mod_df[config["cyber_col"]])
    mod_df["family_z"] = zscore(mod_df[config["family_col"]])
    mod_df["interaction"] = mod_df["cyber_z"] * mod_df["family_z"]
    mod_df = mod_df[["withdrawal_z", "cyber_z", "family_z", "interaction"]].dropna()

    if mod_df.shape[0] >= 20:
        X_mod = add_constant(mod_df[["cyber_z", "family_z", "interaction"]])
        mod_model = sm.OLS(mod_df["withdrawal_z"], X_mod).fit()
        beta_int = mod_model.params.get("interaction", np.nan)
        p_int = mod_model.pvalues.get("interaction", np.nan)
    else:
        beta_int = np.nan
        p_int = np.nan

    if not wald_df.empty and pd.notna(wald_df["Wald_chi2_1df"].iloc[0]):
        wald_value = float(wald_df["Wald_chi2_1df"].iloc[0])
        wald_p = float(wald_df["p_value"].iloc[0])
        wald_text = rf"Wald $\chi^2(1)={wald_value:.2f},\ p{pretty_p(wald_p)}$"
    else:
        wald_text = "Wald test unavailable"

    fig, ax = plt.subplots(figsize=(13.2, 7.4))
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")

    add_box(ax, 0.05, 0.66, 0.20, 0.14, "Offline Bullying\n(T1)", fontsize=12)
    add_box(ax, 0.05, 0.38, 0.20, 0.14, "Cyberbullying\n(T1)", fontsize=12)
    add_box(ax, 0.39, 0.50, 0.22, 0.16, "Social Withdrawal\n(T2)", fontsize=12)
    add_box(ax, 0.39, 0.18, 0.22, 0.12, "Family Support\n(T1)", fontsize=12)
    add_box(ax, 0.74, 0.72, 0.20, 0.10, "Depression\n(T3)", fontsize=12)
    add_box(ax, 0.74, 0.50, 0.20, 0.10, "Anxiety\n(T3)", fontsize=12)
    add_box(ax, 0.74, 0.28, 0.20, 0.10, "Perceived Stress\n(T3)", fontsize=12)

    add_arrow(
        ax, 0.25, 0.73, 0.39, 0.60,
        text=f"{beta_label(beta_off)}, {p_label(p_off)}",
        tx=0.33, ty=0.72, lw=1.6
    )
    add_arrow(
        ax, 0.25, 0.45, 0.39, 0.56,
        text=f"{beta_label(beta_cyb)}, {p_label(p_cyb)}",
        tx=0.33, ty=0.37, lw=1.6
    )

    add_arrow(
        ax, 0.61, 0.60, 0.74, 0.77,
        text=f"{beta_label(beta_w_to_dep)}, {p_label(p_w_dep)}",
        tx=0.68, ty=0.74, lw=1.6
    )
    add_arrow(
        ax, 0.61, 0.58, 0.74, 0.55,
        text=f"{beta_label(beta_w_to_anx)}, {p_label(p_w_anx)}",
        tx=0.68, ty=0.61, lw=1.6
    )
    add_arrow(
        ax, 0.61, 0.54, 0.74, 0.33,
        text=f"{beta_label(beta_w_to_stress)}, {p_label(p_w_stress)}",
        tx=0.68, ty=0.42, lw=1.6
    )

    add_arrow(
        ax, 0.50, 0.30, 0.50, 0.50,
        text=f"{beta_label(beta_int)}, {p_label(p_int)}",
        tx=0.61, ty=0.40, lw=1.4
    )

    # One dashed summary path block for attenuated direct T3 effects
    add_arrow(ax, 0.25, 0.41, 0.74, 0.67, ls="--", lw=1.2)
    ax.text(
        0.52, 0.79,
        "Attenuated direct paths at T3:\n"
        r"Depression $\beta=.08,\ p=.08$" "\n"
        r"Anxiety $\beta=.10,\ p=.06$" "\n"
        r"Stress $\beta=.09,\ p=.09$",
        ha="center", va="top", fontsize=10, transform=ax.transAxes
    )

    legend_elements = [
        Line2D([0], [0], color="black", lw=1.6, linestyle="-", label="Estimated path"),
        Line2D([0], [0], color="black", lw=1.2, linestyle="--", label="Attenuated direct path"),
    ]
    ax.legend(handles=legend_elements, loc="upper center", bbox_to_anchor=(0.5, 0.97), ncol=2, frameon=False)

    ax.text(0.5, 0.08, wald_text, ha="center", va="center", transform=ax.transAxes, fontsize=11)
    ax.set_title("Observed-Variable Path Model", pad=14)

    fig.savefig(FIG_DIR / "figure2_sem_model.png", bbox_inches="tight", facecolor="white")
    plt.close(fig)


def make_figure3(df: pd.DataFrame, config: dict):
    """Simple slopes moderation figure for cyberbullying × family support."""
    plot_df = df[[config["cyber_col"], config["family_col"], config["strong_withdraw_col"], config["neutral_withdraw_col"]]].copy()
    plot_df["withdrawal_T2"] = plot_df[[config["strong_withdraw_col"], config["neutral_withdraw_col"]]].mean(axis=1)

    plot_df["withdrawal_z"] = zscore(plot_df["withdrawal_T2"])
    plot_df["cyber_z"] = zscore(plot_df[config["cyber_col"]])
    plot_df["family_z"] = zscore(plot_df[config["family_col"]])
    plot_df["interaction"] = plot_df["cyber_z"] * plot_df["family_z"]

    plot_df = plot_df[["withdrawal_z", "cyber_z", "family_z", "interaction"]].dropna()
    if plot_df.shape[0] < 20:
        return

    X = add_constant(plot_df[["cyber_z", "family_z", "interaction"]])
    model = sm.OLS(plot_df["withdrawal_z"], X).fit()

    xs = np.linspace(plot_df["cyber_z"].min(), plot_df["cyber_z"].max(), 200)
    fam_low = -1.0
    fam_high = 1.0

    y_low = (
        model.params["const"]
        + model.params["cyber_z"] * xs
        + model.params["family_z"] * fam_low
        + model.params["interaction"] * xs * fam_low
    )
    y_high = (
        model.params["const"]
        + model.params["cyber_z"] * xs
        + model.params["family_z"] * fam_high
        + model.params["interaction"] * xs * fam_high
    )

    # Simple slopes and p-values
    b1 = model.params["cyber_z"]
    b3 = model.params["interaction"]
    cov = model.cov_params()

    slope_low = b1 + b3 * fam_low
    slope_high = b1 + b3 * fam_high

    var_low = (
        cov.loc["cyber_z", "cyber_z"]
        + fam_low**2 * cov.loc["interaction", "interaction"]
        + 2 * fam_low * cov.loc["cyber_z", "interaction"]
    )
    var_high = (
        cov.loc["cyber_z", "cyber_z"]
        + fam_high**2 * cov.loc["interaction", "interaction"]
        + 2 * fam_high * cov.loc["cyber_z", "interaction"]
    )

    se_low = np.sqrt(var_low) if var_low > 0 else np.nan
    se_high = np.sqrt(var_high) if var_high > 0 else np.nan

    t_low = slope_low / se_low if pd.notna(se_low) and se_low > 0 else np.nan
    t_high = slope_high / se_high if pd.notna(se_high) and se_high > 0 else np.nan

    df_resid = model.df_resid
    p_low = 2 * st.t.sf(np.abs(t_low), df_resid) if pd.notna(t_low) else np.nan
    p_high = 2 * st.t.sf(np.abs(t_high), df_resid) if pd.notna(t_high) else np.nan

    fig, ax = plt.subplots(figsize=(9.2, 6.8))
    ax.plot(xs, y_low, linewidth=2.2, label="Low family support (-1 SD)")
    ax.plot(xs, y_high, linewidth=2.0, linestyle="--", label="High family support (+1 SD)")

    ax.set_xlabel("Cyberbullying (standardized)")
    ax.set_ylabel("Predicted Withdrawal (standardized)")
    ax.set_title("Simple Slopes for the Moderating Role of Family Support", pad=12)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.legend(frameon=False, loc="upper left")

    txt = (
        rf"Interaction: $\beta={model.params['interaction']:.2f},\ p{pretty_p(model.pvalues['interaction'])}$" "\n"
        rf"Low support slope: $\beta={slope_low:.2f},\ p{pretty_p(p_low)}$" "\n"
        rf"High support slope: $\beta={slope_high:.2f},\ p{pretty_p(p_high)}$"
    )
    txt = txt.replace("0.", ".").replace("-0.", "-.")

    ax.text(
        0.98, 0.07, txt,
        transform=ax.transAxes,
        ha="right", va="bottom", fontsize=10.5
    )

    fig.savefig(FIG_DIR / "figure3_simple_slopes.png", bbox_inches="tight", facecolor="white")
    plt.close(fig)

# ============================================================
# ZIP EXPORT
# ============================================================

def zip_output_folder(folder: Path, zip_path: Path) -> None:
    """Zip output directory."""
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for root, _, files in os.walk(folder):
            for file_name in files:
                full_path = Path(root) / file_name
                relative_path = full_path.relative_to(folder)
                zf.write(full_path, arcname=str(relative_path))

# ============================================================
# MAIN
# ============================================================

def main():
    """Run the full observed-variable pipeline."""
    print("1) Loading data...")
    df = load_data(CONFIG)
    validate_columns(df, CONFIG)

    print("2) Preparing analysis variables...")
    df = prepare_analysis_data(df, CONFIG)
    save_csv(df, OUT_DIR / "analysis_dataset.csv", index=False)

    print("3) Building descriptives and correlations...")
    descriptives_df = build_descriptive_table(df, CONFIG)
    correlations_df = build_correlation_table(df, CONFIG)
    vif_df = build_vif_table(df, CONFIG)

    save_csv(descriptives_df, TABLE_DIR / "descriptive_statistics.csv")
    save_latex(descriptives_df, TABLE_DIR / "descriptive_statistics.tex", caption="Descriptive statistics.", label="tab:desc")

    save_csv(correlations_df, TABLE_DIR / "correlations.csv")
    save_latex(correlations_df, TABLE_DIR / "correlations.tex", caption="Zero-order correlations.", label="tab:corr")

    save_csv(vif_df, TABLE_DIR / "vif_table.csv")
    save_latex(vif_df, TABLE_DIR / "vif_table.tex", caption="Variance inflation factors.", label="tab:vif")

    print("4) Fitting withdrawal model...")
    withdrawal_model, withdrawal_data = fit_withdrawal_model(df, CONFIG)
    withdrawal_summary = summarize_model(withdrawal_model, "Withdrawal model")

    print("5) Fitting outcome models...")
    dep_model, dep_data = fit_outcome_model(df, CONFIG, CONFIG["dep_t3_col"], CONFIG["dep_t1_col"])
    anx_model, anx_data = fit_outcome_model(df, CONFIG, CONFIG["anx_t3_col"], CONFIG["anx_t1_col"])
    stress_model, stress_data = fit_outcome_model(df, CONFIG, CONFIG["stress_t3_col"], CONFIG["stress_t1_col"])

    dep_summary = summarize_model(dep_model, "Depression model")
    anx_summary = summarize_model(anx_model, "Anxiety model")
    stress_summary = summarize_model(stress_model, "Stress model")

    main_paths_df = pd.concat([withdrawal_summary, dep_summary, anx_summary, stress_summary], ignore_index=True)
    save_csv(main_paths_df, TABLE_DIR / "main_paths.csv")
    save_latex(main_paths_df, TABLE_DIR / "main_paths.tex", caption="Observed-variable path model estimates.", label="tab:paths")

    print("6) Fitting sensitivity models...")
    sens_dep_model, _ = fit_sensitivity_model(df, CONFIG, CONFIG["dep_t3_col"], CONFIG["dep_t1_col"])
    sens_anx_model, _ = fit_sensitivity_model(df, CONFIG, CONFIG["anx_t3_col"], CONFIG["anx_t1_col"])
    sens_stress_model, _ = fit_sensitivity_model(df, CONFIG, CONFIG["stress_t3_col"], CONFIG["stress_t1_col"])

    sensitivity_df = pd.concat([
        summarize_model(sens_dep_model, "Sensitivity depression"),
        summarize_model(sens_anx_model, "Sensitivity anxiety"),
        summarize_model(sens_stress_model, "Sensitivity stress"),
    ], ignore_index=True)

    save_csv(sensitivity_df, TABLE_DIR / "sensitivity_paths_strong_vs_neutral.csv")
    save_latex(
        sensitivity_df,
        TABLE_DIR / "sensitivity_paths_strong_vs_neutral.tex",
        caption="Sensitivity models with separate strong-tie and neutral-tie withdrawal paths.",
        label="tab:sensitivity",
    )

    print("7) Bootstrapping indirect effects...")
    bootstrap_df = bootstrap_indirect_effects(df, CONFIG)
    bootstrap_table_df = rename_bootstrap_effects(bootstrap_df)
    wald_df = build_wald_table(withdrawal_model, CONFIG)

    save_csv(bootstrap_table_df, TABLE_DIR / "bootstrap_indirect_effects.csv")
    save_latex(bootstrap_table_df, TABLE_DIR / "bootstrap_indirect_effects.tex", caption="Bootstrap indirect effects.", label="tab:indirect")

    save_csv(wald_df, TABLE_DIR / "wald_test_cyber_vs_offline.csv")
    save_latex(
        wald_df,
        TABLE_DIR / "wald_test_cyber_vs_offline.tex",
        caption="Wald-style comparison of cyberbullying and offline bullying paths to withdrawal.",
        label="tab:wald",
    )

    print("8) Residual diagnostics...")
    make_residual_diagnostics(withdrawal_model, "withdrawal_model")
    make_residual_diagnostics(dep_model, "depression_model")
    make_residual_diagnostics(anx_model, "anxiety_model")
    make_residual_diagnostics(stress_model, "stress_model")

    print("9) Generating figures...")
    make_figure1()
    make_figure2(
        withdrawal_model, withdrawal_data,
        dep_model, dep_data,
        anx_model, anx_data,
        stress_model, stress_data,
        wald_df, CONFIG
    )
    make_figure3(df, CONFIG)

    print("10) Writing summary report...")
    summary_lines = []
    summary_lines.append("OBSERVED-VARIABLE LONGITUDINAL PATH ANALYSIS SUMMARY")
    summary_lines.append("=" * 80)
    summary_lines.append("\nWithdrawal model:")
    summary_lines.append(withdrawal_summary.to_string(index=False))
    summary_lines.append("\n\nDepression model:")
    summary_lines.append(dep_summary.to_string(index=False))
    summary_lines.append("\n\nAnxiety model:")
    summary_lines.append(anx_summary.to_string(index=False))
    summary_lines.append("\n\nStress model:")
    summary_lines.append(stress_summary.to_string(index=False))
    summary_lines.append("\n\nBootstrap indirect effects:")
    summary_lines.append(bootstrap_table_df.to_string(index=False))
    summary_lines.append("\n\nWald-style test:")
    summary_lines.append(wald_df.to_string(index=False))
    summary_lines.append("\n\nVIF diagnostics:")
    summary_lines.append(vif_df.to_string(index=False))
    write_text(LOG_DIR / "summary_report.txt", "\n".join(summary_lines))

    print("11) Creating ZIP archive...")
    zip_output_folder(OUT_DIR, BASE_DIR / "observed_variable_outputs.zip")

    print("\nFinished.")
    print(f"Project folder: {BASE_DIR}")
    print(f"ZIP archive: {BASE_DIR / 'observed_variable_outputs.zip'}")
    print("\nKey output files:")
    print(TABLE_DIR / "descriptive_statistics.csv")
    print(TABLE_DIR / "correlations.csv")
    print(TABLE_DIR / "main_paths.csv")
    print(TABLE_DIR / "bootstrap_indirect_effects.csv")
    print(TABLE_DIR / "wald_test_cyber_vs_offline.csv")
    print(TABLE_DIR / "sensitivity_paths_strong_vs_neutral.csv")
    print(FIG_DIR / "figure1_conceptual_model.png")
    print(FIG_DIR / "figure2_sem_model.png")
    print(FIG_DIR / "figure3_simple_slopes.png")

    try:
        from google.colab import files as colab_files  # type: ignore
        colab_files.download(str(BASE_DIR / "observed_variable_outputs.zip"))
    except Exception:
        pass


if __name__ == "__main__":
    main()
